name: thwberkeley

channels:
  - conda-forge

dependencies:
  - python=3.6
  - sympy
  - blinker=1.4=py36_0
  - numpy
  - scipy
  - jupyter
  - ipyparallel
  - pandas
  - matplotlib
  - scikit-learn
  - seaborn
  - patsy
  - seaborn
  - tweepy
  - traitlets
  - statsmodels
  - tensorflow
  - scikit-image
  - requests
  - curl
  - xz
  - r-base
  - r-recommended
  - r-irkernel
  - numba
  - beautifulsoup4
  - bokeh
  - julia
  - pip:
    - keras
    - mwapi
    - wikipedia
    - Theano
    - pywikibot
    - docopt
    - getorg
    - tweepy
