name: thwberkeley

dependencies:
  - python>=3.5
  - sympy
  - numpy
  - scipy
  - jupyter
  - ipyparallel
  - pandas
  - matplotlib
  - scikit-learn
  - seaborn
  - patsy
  - seaborn
  - tweepy
  - traitlets
  - statsmodels
  - tensorflow
  - scikit-image
  - requests
  - curl
  - xz
  - r-base
  - r-recommended
  - numba
  - beautifulsoup4
  - bokeh
