name: thwberkeley

channels:
  - conda-forge

dependencies:
  - python>=3.5
  - numpy
  - scipy
  - jupyter
  - pandas
  - matplotlib
  - scikit-learn
  - seaborn
  - tweepy
  - traitlets
  - statsmodels
  - scikit-image
  - requests
  - curl
  - xz
  - r-base
  - r-recommended
  - r-irkernel
  - bokeh
  - julia
  - pip:
    - keras
    - mwapi
    - wikipedia
    - pywikibot
    - docopt
    - getorg
    - tweepy
