permalink: /posts/:year-:month-:day-:title.html

future: true
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
github:
  owner_url: https://github.com/BIDS/DATS
url: https://BIDS.github.io/DATS
name: Data Analysis Tools Series
chapter: Berkeley Institute for Data Science
description: An initial blog and site for DATS at BIDS
twitter: UCBIDS
gravatar_url: http://www.gravatar.com/avatar/0203c034a145af6cc2576d56cdb4cf73
disqus_username: 

