permalink: /posts/:year-:month-:day-:title.html

future: true
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
github:
  owner_url: https://github.com/BIDS/dats
url: https://BIDS.github.io/dats
name: Data Analysis Tools Series
chapter: Berkeley Institute for Data Science
description: DATS at BIDS
twitter: UCBIDS
avatar_url: /images/dats-logo.png
disqus_username: 

